version: '2'
services:
    bellisimo-app:
        image: bellisimo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bellisimo-postgresql:5432/Bellisimo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bellisimo-postgresql:
        extends:
            file: postgresql.yml
            service: bellisimo-postgresql
