#added
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogue
    username: bilal
    password: bilal
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

